---
title: "Clusters"
author: "Peter McNamara"
date: "27th August 2019"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
## ---- load_data  ----
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
library(zoo)
library(shiny)
library(scales)
library(factoextra)
library(lubridate)
library(cluster)

setwd("/GitDev/Footyapp/data/") # use here function instead
FootyGames <- read.csv("FootyGamesClus.csv", stringsAsFactors = FALSE)
team <- "NFC Red"

FootyGames$kickoff_date = as.POSIXct(substr(FootyGames$time, 1, 19), format='%Y-%m-%d %H:%M:%S')
footy_match_play <- FootyGames %>% #filter(playNumber == 1) %>%
  group_by(gameID, competition, ourName, theirName, playNumber) %>%
  arrange(gameID, competition, ourName, theirName, playNumber, sequenceNumber) %>%
  summarise(gameDate = first(kickoff_date),
            playByUs = first(byUs),
            matchName = first(matchName),
            teamName = first(ifelse(playByUs == "true", ourName, theirName)),
            usPhase = first(usPhase),
            half = first(half),
            oppositionPhase = first(oppositionPhase),
            firstEvent = first(adjEventName),
            lastEvent = last(adjEventName),
            Area = first(case_when(lengthFraction <= 0.333333 ~ "Defence",
                                   lengthFraction >= 0.666667 ~ "Attack",
                                   TRUE ~ "Midfield") ),
            lastArea = last(case_when(lengthFraction <= 0.333333 ~ "Defence",
                                      lengthFraction >= 0.666667 ~ "Attack",
                                      TRUE ~ "Midfield") ),
            firstEventArea = paste(firstEvent, "-", Area),
            firstPenalyIncursion = first(penaltyIncursion),
            firstZone = first(zone),
            lastZone = last(zone),
            numSequences = max(sequenceNumber),
            numPlayers = max(player),
            distance = sum(ifelse(lead(byUs) == byUs &
                                    lead(adjEventName) %in% c("first touch", "dribble", "shot", "goal"), 
                                  distanceToNextEventMetres, 0)),
            isAttackIncursion = max(attackIncursion),
            isPenaltyIncursion = max(penaltyIncursion),
            isZone14Incursion = max(ifelse(zone==14 & byUs == playByUs, 1, 0), na.rm=TRUE),
            isZone17Incursion = max(ifelse(zone==17 & byUs == playByUs, 1, 0), na.rm=TRUE),
            playPhase = first(ifelse(playByUs == "true", usPhase, oppositionPhase)),
            totalPasses = sum(adjPass),
            totalBackPasses = sum(isBackPass),
            totalFwdPasses = sum(isFwdPass),
            totalSidePasses = sum(isSidePass),
            total10mPasses = sum(isPass10m),
            total10_20mPasses = sum(isPass10_20m),
            total20mPasses = sum(isPass20m),
            possessionDuration = sum(ifelse(pseudoEvent == FALSE &
                                              byUs == playByUs &
                                              eventName != "keeper", duration, 0)),
            AttackDuration = sum(ifelse(pseudoEvent == FALSE &
                                          byUs == playByUs &
                                          eventName != "keeper" &
                                          Area == "Attack", duration, 0)),
            MidfieldDuration = sum(ifelse(pseudoEvent == FALSE &
                                            byUs == playByUs &
                                            eventName != "keeper" &
                                            Area == "Midfield", duration, 0)),
            DefenceDuration = sum(ifelse(pseudoEvent == FALSE &
                                           byUs == playByUs &
                                           eventName != "keeper" &
                                           Area == "Defence", duration, 0)),
            AttackHalfDuration = sum(ifelse(pseudoEvent == FALSE &
                                              byUs == playByUs &
                                              eventName != "keeper" &
                                              lengthMetres >= 55, duration, 0)),
            DefenceHalfDuration = sum(ifelse(pseudoEvent == FALSE &
                                               byUs == playByUs &
                                               eventName != "keeper" &
                                               lengthMetres < 55, duration, 0)),
            playDuration = sum(duration),
            crossfieldPlay = ifelse(max(widthMetres) - min(widthMetres) > 50, 1, 0),
            goals = sum(ifelse(adjEventName == "goal", 1, 0)),
            shots = sum(ifelse(adjEventName == "shot", 1, 0)) )
footy_match_play$orderCol <- case_when(footy_match_play$teamName == team ~ 0,
                                       footy_match_play$competition %in% c("2019 NSFA 1 Boys Under 13",
                                                                           "2019 NSFA 1 Girls Under 16", "2019 Boys Under 14") ~ 1,
                                       footy_match_play$competition=="2019 International Friendly Mens Open" ~ 2,
                                       footy_match_play$competition=="2019 Icc Football Mens Open" ~ 3,
                                       TRUE ~ 4)
## ---- end-of-load_data  ----
```

## Passes Per Minute

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
footy_match_pca <- footy_match_play %>%
  group_by(competition, gameID, teamName, playByUs) %>%
  summarise(gameDate= min(gameDate),
            theirName = max(theirName),
            gameDuration = sum(possessionDuration),
            gameAttackDurationPcnt = sum(AttackDuration) / gameDuration,
            gameMidfieldDurationPcnt = sum(MidfieldDuration) / gameDuration,
            gameDefenceDurationPcnt = sum(DefenceDuration) / gameDuration,
            gameDistance = sum(distance),
            plays = n(),
            goals = sum(goals),
            shots = sum(shots),
            ppm = sum(totalPasses)/sum(possessionDuration/60),
            attackPlayPcnt = sum(ifelse(lastArea == "Attack", 1, 0)) / plays,
            midfieldPlayPcnt = sum(ifelse(lastArea == "Midfield", 1, 0)) / plays,
            defencePlayPcnt = sum(ifelse(lastArea == "Defence", 1, 0)) / plays,
            penaltyPlayPcnt = sum(ifelse(isPenaltyIncursion == 1, 1, 0)) / plays,
            zone14PlayPcnt = sum(ifelse(isZone14Incursion == 1, 1, 0)) / plays,
            zone17PlayPcnt = sum(ifelse(isZone17Incursion == 1, 1, 0)) / plays,
            backPassPcnt = sum(totalBackPasses) / sum(totalPasses),
            sidePassPcnt = sum(totalSidePasses) / sum(totalPasses),
            fwdPassPcnt = sum(totalFwdPasses) / sum(totalPasses),
            Pass10mPcnt = sum(total10mPasses) / sum(total10mPasses + total10_20mPasses + total20mPasses),
            Pass10_20mPcnt = sum(total10_20mPasses) / sum(total10mPasses + total10_20mPasses + total20mPasses),
            Pass20mPcnt = sum(total20mPasses) / sum(total10mPasses + total10_20mPasses + total20mPasses),
            noPassPlayPcnt = sum(ifelse(totalPasses == 0, 1, 0)) / plays,
            passPlayPcnt = sum(ifelse(totalPasses > 1, 1, 0)) / plays,
            Plays1_3PassesPcnt = sum(ifelse(totalPasses > 0 & totalPasses <= 3, 1, 0)) / plays,
            Plays4_6PassesPcnt = sum(ifelse(totalPasses > 3 & totalPasses <= 6, 1, 0)) / plays,
            Plays7PlusPassesPcnt = sum(ifelse(totalPasses > 6, 1, 0)) / plays,
            playsAttTurn = sum(ifelse(Area == "Attack" & firstEvent == "first touch", 1, 0)),
            matchName = max(matchName)
  ) 

fmpca <- as.data.frame(footy_match_pca)
#rownames(fmpca) <- paste(gsub('\\b(\\pL)\\pL{0,}|.','\\U\\1',fmpca$teamName,perl = TRUE), case_when(fmpca$teamName == "Beaconhill" ~ "H",
                                                              #                                      fmpca$teamName == "W Pymble" ~ "W",
                                                              #                                      fmpca$teamName == "NFC White" ~ "W",
                                                               #                                     fmpca$teamName == "STU" ~ "TU",
                                                                #                                   fmpca$competition == "2019 NSFA 1 Girls Under 16" ~ "16",
#TRUE ~ "") )

fmpca.pr <- prcomp(fmpca[c(7:9, 15:31)], center = TRUE, scale = TRUE)

fviz_pca_ind(fmpca.pr, geom = c("point"),
             pointshape = 21, 
             pointsize = 2, 
             fill.ind = ifelse(fmpca$competition=="2019 NSFA 1 Boys Under 13", ifelse(fmpca$), "Top Flight Teams"), #paste(fmpca$matchName, fmpca$result), 
             col.ind = "black", 
           #  palette = "Set1", 
             addEllipses = FALSE,
           #  label  = "var",
             col.var = "black",
             repel = TRUE,
             mean.point = FALSE,
             legend.title = "Result") +
  ggtitle("2D PCA-plot") +
  theme(plot.title = element_text(hjust = 0.5)#,
       # legend.position = "none"
       )
```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
fviz_pca_var(fmpca.pr, geom = c("point", "text"),
             col.var="steel blue",
             repel = TRUE)+
  theme_minimal()

```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
fviz_pca_biplot(fmpca.pr, geom = c("point", "text"),
             col.var="green",
             pointshape = 21, 
             pointsize = 2, 
             fill.ind = ifelse(fmpca$competition=="2019 NSFA 1 Girls Under 16", "16 Girls", "Others"),
             alpha.var = 0.2, 
             repel = TRUE,
             mean.point = FALSE)+
  theme_minimal()

```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}

m<-as.matrix(fmpca[c(7:9, 15:31)])
d <- dist(m)

#kmeans clustering
#kmeans - run with nstart=100 and k=2,3,5 to compare results with hclust
#kfit <- kmeans(d, 3, nstart=100)
#plot - need library cluster
#clusplot(as.matrix(d), kfit$cluster, color=T, shade=T, labels=2, lines=0)

#rerun using cosine distance
cosineSim <- function(x){
  as.dist(x%*%t(x)/(sqrt(rowSums(x^2) %*% t(rowSums(x^2)))))
}
cs <- cosineSim(m)
cd <- 1-cs

kfit <- kmeans(cd, 3, nstart=1000)

clusplot(as.matrix(cd), kfit$cluster, color=T, shade=T, labels=2, lines=0)
```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
#groups <- hclust(d,method="ward.D")
#plot, use hang to ensure that labels fall below tree
#plot(groups, hang=-1)
#cut into 2 subtrees. Try 3,4,5,6 cuts; comment on your results
#rect.hclust(groups,3)
#hclusters <- cutree(groups,3)

groups <- hclust(cd,method="ward.D")
#plot, use hang to ensure that labels fall below tree
#plot(groups, hang=-1)
#rect.hclust(groups,3)
```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
fviz_cluster(kfit, cd, ellipse = TRUE, ellipse.alpha= 0.1,
             palette = "jco",repel = TRUE, ggtheme = theme_minimal(), 
             main= FALSE, xlab= FALSE, ylab = FALSE)

```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center", fig.width=10, fig.height=10}
rownames(fmpca) <- fmpca$teamName
m<-as.matrix(fmpca[c(7:9, 15:31)])
cs <- cosineSim(m)
cd <- 1-cs
groups <- hclust(cd,method="ward.D")

```

```{r echo=FALSE, message=FALSE, eval=TRUE, fig.align ="center"}
# Visualize using factoextra
fviz_dend(groups, k = 3, # Cut in 8 groups
          cex = 0.5, # label size
          horiz= TRUE, rect = TRUE # Add rectangle around groups
)


```